http:
  host: 127.0.0.1
  port: 3000

jwt:
  secret: secretKey
  signOptions:
    expiresIn: 10m

bull:
  redis:
    host: localhost
    port: 6379

db:
  typeorm:
    type: mysql
    database: graphql-test
    username: root
    password: password

    synchronize: false
    keepConnectionAlive: false

    entities:
      - src/**/*.entity{.ts,.js}
    migrations:
      - src/db/migrations/*{.ts,.js}
    subscribers:
      - src/db/subscribers/*{.ts,.js}
    cli:
      entitiesDir: src/**/*.entity{.ts,.js},
      migrationsDir: src/db/migrations
      subscribersDir: src/db/subscribers

  redis:
    host: localhost
    port: 6379
    ttl: 0

notion:
  integrationToken: secret_NCeq9uOaZ8teuBF6DfDIE26Vi2zlyqrjlrdJ7a4VoPp
  databaseID: cc54173915bf480f98fe0a7957a609f6
