http:
  host: 127.0.0.1
  port: 3000

jwt:
  secret: secretKey
  signOptions:
    expiresIn: 15m

db:
  typeorm:
    type: mysql
    database: graphql
    username: root
    password: password
    keepConnectionAlive: false

    entities:
      - src/**/*.entity{.ts,.js}
    migrations:
      - src/db/migrations/*{.ts,.js}
    subscribers:
      - src/db/subscribers/*{.ts,.js}
    cli:
      entitiesDir: src/**/*.entity{.ts,.js},
      migrationsDir: src/db/migrations,
      subscribersDir: src/db/subscribers

  redis:
    host: localhost
    port: 6379
    ttl: 0
