name: Build Docker image

on:
  push:
    branches:
      - 'master'
      - 'actions-test'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build & push the Docker image for ARM64 arch
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: chem-graphql
        IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
      run: |
        docker buildx build --platform linux/arm64/v8 -t chem-graphql:latest .
        docker tag chem-graphql:latest 590624982938.dkr.ecr.eu-west-2.amazonaws.com/chem-graphql:latest
        docker push 590624982938.dkr.ecr.eu-west-2.amazonaws.com/chem-graphql:latest
