name: Run unit tests

on:
  push:
    branches: 
      - master
      - actions-test

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 17.2.0
        cache: 'npm'

    - name: Install the dependencies
      run: npm run ci

    - name: Build the Nest.js app
      run: npm run build --if-present

#     - name: Run the tests
#       run: npm test
